--DROP TABLE IF EXISTS users CASCADE;
--DROP TABLE IF EXISTS feeds;


CREATE TABLE users (
	username TEXT PRIMARY KEY UNIQUE NOT NULL,
	password TEXT NOT NULL,
	date_created DATE DEFAULT CURRENT_DATE
);

CREATE TABLE feeds (
	id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY, 
	username TEXT  NOT NULL REFERENCES users,
	url TEXT NOT NULL,
	content XML 
);
